# Generated by Django 5.2.5 on 2025-09-05 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productrating', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productrating',
            name='unique_product_user',
        ),
    ]
