# Generated by Django 5.2.5 on 2025-09-05 07:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productrating', '0002_remove_productrating_unique_product_user'),
        ('products', '0005_product_sold'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productrating',
            constraint=models.UniqueConstraint(fields=('product', 'user'), name='unique_product_user'),
        ),
    ]
