# Generated by Django 5.2.5 on 2025-09-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productrating', '0003_productrating_unique_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrating',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
