# Generated by Django 5.2.5 on 2025-09-05 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productrating', '0005_alter_productrating_product'),
        ('products', '0005_product_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrating',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_ratings', to='products.product'),
        ),
    ]
