# Generated by Django 5.2.5 on 2025-08-21 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_product_fileid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
