# Generated by Django 5.2.5 on 2025-10-01 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0002_checkout_address_checkout_city_checkout_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='shipping_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='subtotal_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='checkoutproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
