# Generated by Django 5.2.5 on 2025-10-02 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='coupon_code',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='shipping_method',
        ),
        migrations.AddField(
            model_name='checkout',
            name='phone_code',
            field=models.CharField(blank=True, default='+234', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='remaining_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.CreateModel(
            name='InstallmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('receipt_url', models.URLField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rn_installments', to='checkouts.checkout')),
            ],
        ),
    ]
