# Generated by Django 5.2.5 on 2025-10-03 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0003_remove_checkout_coupon_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='receipt_url',
        ),
        migrations.RemoveField(
            model_name='installmentpayment',
            name='receipt_url',
        ),
    ]
