# Generated by Django 5.2.5 on 2025-10-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0004_remove_checkout_receipt_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='payment_channel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='installmentpayment',
            name='payment_channel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
