# Generated by Django 5.2.5 on 2025-10-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0005_checkout_payment_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='pod_account_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='pod_account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='pod_bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
