# Generated by Django 5.2.5 on 2025-10-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0006_checkout_pod_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentpayment',
            name='installment_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
