# Generated by Django 5.2.5 on 2025-10-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0008_alter_checkout_checkoutid'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='lga',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='subArea',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
