# Generated by Django 5.2.5 on 2025-10-20 03:36

import checkouts.generate_rerference
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0009_checkout_lga_checkout_subarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='checkoutID',
            field=models.CharField(db_index=True, default=checkouts.generate_rerference.generate_checkout_id, max_length=32, unique=True),
        ),
    ]
