# Generated by Django 5.2.5 on 2025-10-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0010_alter_checkout_checkoutid'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='currencySym',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
