# Generated by Django 5.2.5 on 2025-10-23 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0011_checkout_currencysym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='currencySym',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
