# Generated by Django 5.2.5 on 2025-10-15 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffFCMToken',
        ),
    ]
