# Generated by Django 5.2.5 on 2025-10-20 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_stafffcmtoken_architecture_stafffcmtoken_browsername_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stafffcmtoken',
            name='fcm_token',
            field=models.CharField(max_length=255),
        ),
    ]
