# Generated by Django 5.2.5 on 2025-09-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='fileId',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
