# Generated by Django 5.2.5 on 2025-10-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_email_address',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
