# Generated by Django 5.2.5 on 2025-09-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_store_fileid_store_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='active', max_length=20),
        ),
    ]
