# Generated by Django 5.2.5 on 2025-09-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_store_store_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
