# Generated by Django 5.2.5 on 2025-08-20 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsadvert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productadvert',
            name='discount',
            field=models.CharField(max_length=200),
        ),
    ]
