# Generated by Django 5.2.5 on 2025-08-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsadvert', '0002_alter_productadvert_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='productadvert',
            name='fileId',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
