# Generated by Django 5.2.5 on 2025-10-01 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureAdvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchor', models.CharField(max_length=200)),
                ('paragraph', models.TextField()),
                ('heading', models.CharField(max_length=200)),
            ],
        ),
    ]
