# Generated by Django 5.2.5 on 2025-10-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featuresadvert', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureAdvertImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('fileId', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
