# Generated by Django 5.2.5 on 2025-10-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paystack_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
