# Generated by Django 5.2.5 on 2025-10-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_paystack_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lga',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subArea',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
