# Generated by Django 5.2.5 on 2025-08-28 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_phone_user_mobile_no_user_city_user_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone_code',
            new_name='phoneCode',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='state_code',
            new_name='stateCode',
        ),
    ]
