# Generated by Django 5.2.5 on 2025-09-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cityId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='countryId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='stateId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
