# Generated by Django 5.2.5 on 2025-09-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_cityid_user_countryid_user_stateid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hasCities',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='hasStates',
            field=models.BooleanField(default=False),
        ),
    ]
