# Generated by Django 5.2.5 on 2025-09-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_is_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='countryEmoji',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='currency',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='currencyName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='currencySymbol',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
