# Generated by Django 5.2.5 on 2025-09-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_countryemoji_user_currency_user_currencyname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='countryEmoji',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
