# Generated by Django 5.2.5 on 2025-10-01 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rn_subcategories', to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('fullDescription', models.TextField()),
                ('marketingDescription', models.TextField(blank=True, null=True)),
                ('marketPrice', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discountPrice', models.DecimalField(decimal_places=2, max_digits=12)),
                ('numberOfItems', models.IntegerField(default=1)),
                ('thumbnail_url_0', models.URLField(blank=True, null=True)),
                ('image_url_0', models.URLField(blank=True, null=True)),
                ('fileId_0', models.CharField(blank=True, max_length=200, null=True)),
                ('image_url_1', models.URLField(blank=True, null=True)),
                ('fileId_1', models.CharField(blank=True, max_length=200, null=True)),
                ('image_url_2', models.URLField(blank=True, null=True)),
                ('fileId_2', models.CharField(blank=True, max_length=200, null=True)),
                ('image_url_3', models.URLField(blank=True, null=True)),
                ('fileId_3', models.CharField(blank=True, max_length=200, null=True)),
                ('image_url_4', models.URLField(blank=True, null=True)),
                ('fileId_4', models.CharField(blank=True, max_length=200, null=True)),
                ('sold', models.BooleanField(default=False)),
                ('noOfReviewers', models.IntegerField(default=0)),
                ('technicalDescription', models.TextField(blank=True, null=True)),
                ('techFeature_1', models.CharField(blank=True, max_length=200, null=True)),
                ('techFeature_2', models.CharField(blank=True, max_length=200, null=True)),
                ('techFeature_3', models.CharField(blank=True, max_length=200, null=True)),
                ('techFeature_4', models.CharField(blank=True, max_length=200, null=True)),
                ('techFeature_5', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.ManyToManyField(blank=True, related_name='rn_category_products', to='products.category')),
            ],
        ),
    ]
