# Generated by Django 5.2.5 on 2025-10-01 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='numberOfItems',
            new_name='numberOfItemsAvailable',
        ),
    ]
