# Generated by Django 5.2.5 on 2025-08-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_fulldescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fullDescription',
            field=models.TextField(),
        ),
    ]
