# Generated by Django 5.2.5 on 2025-08-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_fulldescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fileId',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
