# Generated by Django 5.2.5 on 2025-09-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='marketingDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='technicalDescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
