# Generated by Django 5.2.5 on 2025-09-10 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_marketingdescription_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='fileId',
            new_name='fileId_1',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image_url',
            new_name='image_url_1',
        ),
        migrations.AddField(
            model_name='product',
            name='fileId_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fileId_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fileId_4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url_3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url_4',
            field=models.URLField(blank=True, null=True),
        ),
    ]
