# Generated by Django 5.2.5 on 2025-09-12 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_fileid_product_fileid_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='fileId_1',
            new_name='fileId_0',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image_url_1',
            new_name='image_url_0',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fileId_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fileId_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fileId_4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url_4',
        ),
    ]
