# Generated by Django 5.2.5 on 2025-09-14 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_fileid_1_product_fileid_2_product_fileid_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fileId_4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url_4',
            field=models.URLField(blank=True, null=True),
        ),
    ]
