# Generated by Django 5.2.5 on 2025-09-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_fileid_4_product_image_url_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='techFeature_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='techFeature_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='techFeature_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='techFeature_4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='techFeature_5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
