# Generated by Django 5.2.5 on 2025-09-20 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_techfeature_1_product_techfeature_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail_url_0',
            field=models.URLField(blank=True, null=True),
        ),
    ]
