# Generated by Django 5.2.5 on 2025-09-22 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_thumbnail_url_0'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='numberOfItems',
            field=models.IntegerField(default=1),
        ),
    ]
