# Generated by Django 5.2.5 on 2025-09-27 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
