# Generated by Django 5.2.5 on 2025-10-01 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discountPrice',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='marketPrice',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
